name: Generate Banner

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate banner
        env:
          NEVERLAND_KEY: ${{ secrets.NEVERLAND_KEY }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: pnpm generate:banner

      - name: Commit changes
        run: |
          git config user.name "cuzknothz"
          git config user.email "cuzknothz@gmail.com"
          git add banner/finalize_banner.svg
          if git diff --cached --quiet; then
            git commit --allow-empty -m "🩵"
          else
            git commit -m "🩵"
          fi
          git push
